import type { Visit, VisitInput } from '../types';

const visits: Visit[] = [
  {
    id: 'v-001',
    patientId: 'p-001',
    condition: 'hypertension',
    vitals: [
      { key: 'systolic', label: 'Systolic BP', value: 142, unit: 'mmHg' },
      { key: 'diastolic', label: 'Diastolic BP', value: 88, unit: 'mmHg' },
      { key: 'pulse', label: 'Pulse Rate', value: 78, unit: 'bpm' },
    ],
    severity: 'moderate',
    notes: 'Patient reports elevated BP. Continue monitoring and review medications.',
    prescription: 'Amlodipine 5mg once daily, low-sodium diet',
    followUp: '2 weeks',
    doctorName: 'Dr. Arjun Mehta',
    visitDate: '2026-08-15T09:00:00.000Z',
    createdAt: '2026-08-15T09:00:00.000Z',
  },
  {
    id: 'v-002',
    patientId: 'p-002',
    condition: 'fever',
    vitals: [
      { key: 'temperature', label: 'Temperature', value: 101.2, unit: '°F' },
      { key: 'spo2', label: 'Oxygen Saturation', value: 97, unit: '%' },
      { key: 'pulse', label: 'Pulse Rate', value: 92, unit: 'bpm' },
    ],
    severity: 'moderate',
    notes: 'Fever subsiding. Schedule follow-up in 3 days if symptoms persist.',
    prescription: 'Paracetamol 500mg every 6 hours, plenty of fluids',
    followUp: '3 days',
    doctorName: 'Dr. Sneha Iyer',
    visitDate: '2026-08-20T11:30:00.000Z',
    createdAt: '2026-08-20T11:30:00.000Z',
  },
  {
    id: 'v-003',
    patientId: 'p-001',
    condition: 'general',
    vitals: [
      { key: 'temperature', label: 'Temperature', value: 98.4, unit: '°F' },
      { key: 'bloodPressure', label: 'Blood Pressure', value: '118/76', unit: 'mmHg' },
      { key: 'pulse', label: 'Pulse Rate', value: 72, unit: 'bpm' },
    ],
    severity: 'mild',
    notes: 'Routine follow-up. Patient reports feeling well.',
    prescription: 'Continue current medications',
    followUp: '1 month',
    doctorName: 'Dr. Arjun Mehta',
    visitDate: '2026-08-25T10:00:00.000Z',
    createdAt: '2026-08-25T10:00:00.000Z',
  },
  {
    id: 'v-004',
    patientId: 'p-003',
    condition: 'diabetes',
    vitals: [
      { key: 'fastingGlucose', label: 'Fasting Blood Glucose', value: 126, unit: 'mg/dL' },
      { key: 'hba1c', label: 'HbA1c', value: 6.8, unit: '%' },
      { key: 'weight', label: 'Weight', value: 82, unit: 'kg' },
    ],
    severity: 'moderate',
    notes: 'HbA1c slightly elevated. Adjust diet plan and recheck in 4 weeks.',
    prescription: 'Metformin 500mg twice daily, dietary counseling referral',
    followUp: '4 weeks',
    doctorName: 'Dr. Priya Nair',
    visitDate: '2026-08-28T14:00:00.000Z',
    createdAt: '2026-08-28T14:00:00.000Z',
  },
  {
    id: 'v-005',
    patientId: 'p-002',
    condition: 'general',
    vitals: [
      { key: 'temperature', label: 'Temperature', value: 98.1, unit: '°F' },
      { key: 'bloodPressure', label: 'Blood Pressure', value: '112/70', unit: 'mmHg' },
      { key: 'pulse', label: 'Pulse Rate', value: 68, unit: 'bpm' },
    ],
    severity: 'mild',
    notes: 'Post-fever checkup. Vitals within normal range.',
    doctorName: 'Dr. Sneha Iyer',
    visitDate: '2026-09-01T10:30:00.000Z',
    createdAt: '2026-09-01T10:30:00.000Z',
  },
  {
    id: 'v-006',
    patientId: 'p-005',
    condition: 'hypertension',
    vitals: [
      { key: 'systolic', label: 'Systolic BP', value: 156, unit: 'mmHg' },
      { key: 'diastolic', label: 'Diastolic BP', value: 94, unit: 'mmHg' },
      { key: 'pulse', label: 'Pulse Rate', value: 84, unit: 'bpm' },
    ],
    severity: 'severe',
    notes: 'BP significantly elevated. Medication adjustment recommended.',
    prescription: 'Losartan 50mg daily, Hydrochlorothiazide 12.5mg daily',
    followUp: '1 week',
    doctorName: 'Dr. Arjun Mehta',
    visitDate: '2026-09-02T15:00:00.000Z',
    createdAt: '2026-09-02T15:00:00.000Z',
  },
  {
    id: 'v-007',
    patientId: 'p-006',
    condition: 'fever',
    vitals: [
      { key: 'temperature', label: 'Temperature', value: 100.4, unit: '°F' },
      { key: 'spo2', label: 'Oxygen Saturation', value: 98, unit: '%' },
      { key: 'pulse', label: 'Pulse Rate', value: 88, unit: 'bpm' },
    ],
    severity: 'moderate',
    notes: 'Low-grade fever. Advised rest and hydration.',
    prescription: 'Paracetamol 650mg as needed, ORS sachets',
    followUp: '3 days if fever persists',
    doctorName: 'Dr. Kavya Rao',
    visitDate: '2026-09-03T11:15:00.000Z',
    createdAt: '2026-09-03T11:15:00.000Z',
  },
  {
    id: 'v-008',
    patientId: 'p-007',
    condition: 'diabetes',
    vitals: [
      { key: 'fastingGlucose', label: 'Fasting Blood Glucose', value: 118, unit: 'mg/dL' },
      { key: 'hba1c', label: 'HbA1c', value: 6.2, unit: '%' },
      { key: 'weight', label: 'Weight', value: 78, unit: 'kg' },
    ],
    severity: 'mild',
    notes: 'Glucose levels improved since last visit.',
    prescription: 'Continue Metformin 500mg, maintain exercise routine',
    followUp: '6 weeks',
    doctorName: 'Dr. Priya Nair',
    visitDate: '2026-09-04T09:45:00.000Z',
    createdAt: '2026-09-04T09:45:00.000Z',
  },
  {
    id: 'v-009',
    patientId: 'p-008',
    condition: 'general',
    vitals: [
      { key: 'temperature', label: 'Temperature', value: 98.6, unit: '°F' },
      { key: 'bloodPressure', label: 'Blood Pressure', value: '120/80', unit: 'mmHg' },
      { key: 'pulse', label: 'Pulse Rate', value: 74, unit: 'bpm' },
      { key: 'weight', label: 'Weight', value: 65, unit: 'kg' },
    ],
    severity: 'mild',
    notes: 'Annual wellness check. All vitals normal.',
    doctorName: 'Dr. Sneha Iyer',
    visitDate: '2026-09-05T14:00:00.000Z',
    createdAt: '2026-09-05T14:00:00.000Z',
  },
  {
    id: 'v-010',
    patientId: 'p-003',
    condition: 'hypertension',
    vitals: [
      { key: 'systolic', label: 'Systolic BP', value: 138, unit: 'mmHg' },
      { key: 'diastolic', label: 'Diastolic BP', value: 86, unit: 'mmHg' },
      { key: 'pulse', label: 'Pulse Rate', value: 76, unit: 'bpm' },
    ],
    severity: 'moderate',
    notes: 'Follow-up for combined diabetes and hypertension management.',
    prescription: 'Amlodipine 5mg + Metformin 500mg, salt-restricted diet',
    followUp: '3 weeks',
    doctorName: 'Dr. Arjun Mehta',
    visitDate: '2026-09-06T10:00:00.000Z',
    createdAt: '2026-09-06T10:00:00.000Z',
  },
  {
    id: 'v-011',
    patientId: 'p-009',
    condition: 'fever',
    vitals: [
      { key: 'temperature', label: 'Temperature', value: 102.1, unit: '°F' },
      { key: 'spo2', label: 'Oxygen Saturation', value: 96, unit: '%' },
      { key: 'pulse', label: 'Pulse Rate', value: 96, unit: 'bpm' },
    ],
    severity: 'moderate',
    notes: 'High fever with chills. Prescribed antipyretics.',
    prescription: 'Ibuprofen 400mg TDS, tepid sponging, blood tests ordered',
    followUp: '2 days',
    doctorName: 'Dr. Kavya Rao',
    visitDate: '2026-09-07T08:30:00.000Z',
    createdAt: '2026-09-07T08:30:00.000Z',
  },
  {
    id: 'v-012',
    patientId: 'p-010',
    condition: 'diabetes',
    vitals: [
      { key: 'fastingGlucose', label: 'Fasting Blood Glucose', value: 145, unit: 'mg/dL' },
      { key: 'hba1c', label: 'HbA1c', value: 7.4, unit: '%' },
      { key: 'weight', label: 'Weight', value: 71, unit: 'kg' },
    ],
    severity: 'severe',
    notes: 'Poor glycemic control. Refer to dietician.',
    prescription: 'Glimepiride 2mg daily, Metformin 1000mg, dietician referral',
    followUp: '2 weeks',
    doctorName: 'Dr. Priya Nair',
    visitDate: '2026-09-08T13:20:00.000Z',
    createdAt: '2026-09-08T13:20:00.000Z',
  },
  {
    id: 'v-013',
    patientId: 'p-001',
    condition: 'hypertension',
    vitals: [
      { key: 'systolic', label: 'Systolic BP', value: 128, unit: 'mmHg' },
      { key: 'diastolic', label: 'Diastolic BP', value: 82, unit: 'mmHg' },
      { key: 'pulse', label: 'Pulse Rate', value: 70, unit: 'bpm' },
    ],
    severity: 'mild',
    notes: 'BP improving on current medication regimen.',
    prescription: 'Continue Amlodipine 5mg, add walking 30 min daily',
    followUp: '1 month',
    doctorName: 'Dr. Arjun Mehta',
    visitDate: '2026-09-09T11:00:00.000Z',
    createdAt: '2026-09-09T11:00:00.000Z',
  },
  {
    id: 'v-014',
    patientId: 'p-011',
    condition: 'general',
    vitals: [
      { key: 'temperature', label: 'Temperature', value: 98.2, unit: '°F' },
      { key: 'bloodPressure', label: 'Blood Pressure', value: '110/68', unit: 'mmHg' },
      { key: 'pulse', label: 'Pulse Rate', value: 66, unit: 'bpm' },
    ],
    severity: 'mild',
    notes: 'Sports injury follow-up. No complications.',
    followUp: '2 weeks',
    doctorName: 'Dr. Sneha Iyer',
    visitDate: '2026-09-10T16:45:00.000Z',
    createdAt: '2026-09-10T16:45:00.000Z',
  },
  {
    id: 'v-015',
    patientId: 'p-012',
    condition: 'fever',
    vitals: [
      { key: 'temperature', label: 'Temperature', value: 99.8, unit: '°F' },
      { key: 'spo2', label: 'Oxygen Saturation', value: 99, unit: '%' },
      { key: 'pulse', label: 'Pulse Rate', value: 80, unit: 'bpm' },
    ],
    severity: 'mild',
    notes: 'Mild viral fever. Symptomatic treatment advised.',
    prescription: 'Paracetamol 500mg SOS, adequate rest',
    followUp: '5 days if symptoms persist',
    doctorName: 'Dr. Kavya Rao',
    visitDate: '2026-09-11T09:30:00.000Z',
    createdAt: '2026-09-11T09:30:00.000Z',
  },
  {
    id: 'v-016',
    patientId: 'p-005',
    condition: 'general',
    vitals: [
      { key: 'temperature', label: 'Temperature', value: 98.0, unit: '°F' },
      { key: 'bloodPressure', label: 'Blood Pressure', value: '130/84', unit: 'mmHg' },
      { key: 'pulse', label: 'Pulse Rate', value: 72, unit: 'bpm' },
    ],
    severity: 'mild',
    notes: 'BP follow-up after medication change.',
    prescription: 'Continue Losartan 50mg, monitor BP at home',
    followUp: '2 weeks',
    doctorName: 'Dr. Arjun Mehta',
    visitDate: '2026-09-12T10:15:00.000Z',
    createdAt: '2026-09-12T10:15:00.000Z',
  },
  {
    id: 'v-017',
    patientId: 'p-013',
    condition: 'hypertension',
    vitals: [
      { key: 'systolic', label: 'Systolic BP', value: 148, unit: 'mmHg' },
      { key: 'diastolic', label: 'Diastolic BP', value: 90, unit: 'mmHg' },
      { key: 'pulse', label: 'Pulse Rate', value: 82, unit: 'bpm' },
    ],
    severity: 'moderate',
    notes: 'New patient with stage 1 hypertension.',
    prescription: 'Telmisartan 40mg daily, lifestyle modifications counseling',
    followUp: '2 weeks',
    doctorName: 'Dr. Arjun Mehta',
    visitDate: '2026-09-13T14:30:00.000Z',
    createdAt: '2026-09-13T14:30:00.000Z',
  },
  {
    id: 'v-018',
    patientId: 'p-002',
    condition: 'diabetes',
    vitals: [
      { key: 'fastingGlucose', label: 'Fasting Blood Glucose', value: 105, unit: 'mg/dL' },
      { key: 'hba1c', label: 'HbA1c', value: 5.9, unit: '%' },
    ],
    severity: 'mild',
    notes: 'Screening test — prediabetic range. Lifestyle counseling provided.',
    prescription: 'No medication, dietary changes and exercise recommended',
    followUp: '3 months',
    doctorName: 'Dr. Priya Nair',
    visitDate: '2026-09-14T11:00:00.000Z',
    createdAt: '2026-09-14T11:00:00.000Z',
  },
  {
    id: 'v-019',
    patientId: 'p-007',
    condition: 'general',
    vitals: [
      { key: 'temperature', label: 'Temperature', value: 98.4, unit: '°F' },
      { key: 'bloodPressure', label: 'Blood Pressure', value: '124/78', unit: 'mmHg' },
      { key: 'pulse', label: 'Pulse Rate', value: 70, unit: 'bpm' },
    ],
    severity: 'mild',
    notes: 'Routine diabetes management follow-up.',
    prescription: 'Continue Metformin 500mg, quarterly HbA1c test',
    followUp: '6 weeks',
    doctorName: 'Dr. Priya Nair',
    visitDate: '2026-09-14T15:30:00.000Z',
    createdAt: '2026-09-14T15:30:00.000Z',
  },
  {
    id: 'v-020',
    patientId: 'p-014',
    condition: 'fever',
    vitals: [
      { key: 'temperature', label: 'Temperature', value: 101.5, unit: '°F' },
      { key: 'spo2', label: 'Oxygen Saturation', value: 97, unit: '%' },
      { key: 'pulse', label: 'Pulse Rate', value: 90, unit: 'bpm' },
    ],
    severity: 'moderate',
    notes: 'Upper respiratory infection suspected.',
    prescription: 'Azithromycin 500mg x 3 days, Paracetamol 650mg TDS, steam inhalation',
    followUp: '3 days',
    doctorName: 'Dr. Kavya Rao',
    visitDate: '2026-09-15T08:00:00.000Z',
    createdAt: '2026-09-15T08:00:00.000Z',
  },
  {
    id: 'v-021',
    patientId: 'p-005',
    condition: 'asthma',
    vitals: [
      { key: 'respiratoryRate', label: 'Respiratory Rate', value: 22, unit: 'breaths/min' },
      { key: 'spo2', label: 'Oxygen Saturation', value: 96, unit: '%' },
      { key: 'peakFlow', label: 'Peak Expiratory Flow', value: 320, unit: 'L/min' },
      { key: 'pulse', label: 'Pulse Rate', value: 88, unit: 'bpm' },
      { key: 'wheezing', label: 'Wheezing Present', value: true },
      { key: 'inhalerUsed', label: 'Inhaler Used Today', value: true },
    ],
    severity: 'moderate',
    notes: 'Mild asthma exacerbation. Inhaler prescribed and technique reviewed.',
    prescription: 'Salbutamol inhaler 2 puffs PRN, Budesonide 200mcg BD',
    followUp: '1 week',
    doctorName: 'Dr. Sneha Iyer',
    visitDate: '2026-09-12T10:30:00.000Z',
    createdAt: '2026-09-12T10:30:00.000Z',
  },
  {
    id: 'v-022',
    patientId: 'p-008',
    condition: 'cardiac',
    vitals: [
      { key: 'systolic', label: 'Systolic BP', value: 138, unit: 'mmHg' },
      { key: 'diastolic', label: 'Diastolic BP', value: 86, unit: 'mmHg' },
      { key: 'pulse', label: 'Pulse Rate', value: 94, unit: 'bpm' },
      { key: 'spo2', label: 'Oxygen Saturation', value: 97, unit: '%' },
      { key: 'chestPainScore', label: 'Chest Pain Score', value: 4, unit: '0-10' },
      { key: 'shortnessOfBreath', label: 'Shortness of Breath', value: true },
      { key: 'ecgNotes', label: 'ECG / Clinical Notes', value: 'Sinus tachycardia. No ST changes.' },
    ],
    severity: 'moderate',
    notes: 'Chest discomfort on exertion. ECG ordered and cardiology referral suggested.',
    prescription: 'Aspirin 75mg daily, ECG report review, cardiology referral',
    followUp: '1 week',
    doctorName: 'Dr. Arjun Mehta',
    visitDate: '2026-09-10T14:00:00.000Z',
    createdAt: '2026-09-10T14:00:00.000Z',
  },
  {
    id: 'v-023',
    patientId: 'p-011',
    condition: 'anemia',
    vitals: [
      { key: 'hemoglobin', label: 'Hemoglobin', value: 9.2, unit: 'g/dL' },
      { key: 'pulse', label: 'Pulse Rate', value: 102, unit: 'bpm' },
      { key: 'bloodPressure', label: 'Blood Pressure', value: '110/70', unit: 'mmHg' },
      { key: 'weight', label: 'Weight', value: 54, unit: 'kg' },
      { key: 'pallor', label: 'Pallor Present', value: true },
      { key: 'fatigue', label: 'Fatigue Reported', value: true },
    ],
    severity: 'moderate',
    notes: 'Moderate iron-deficiency anemia. Iron supplementation started.',
    prescription: 'Ferrous sulfate 200mg BD with Vitamin C, iron-rich diet',
    followUp: '4 weeks',
    doctorName: 'Dr. Priya Nair',
    visitDate: '2026-09-08T09:15:00.000Z',
    createdAt: '2026-09-08T09:15:00.000Z',
  },
];

function sortByVisitDateDesc(list: Visit[]) {
  return [...list].sort(
    (a, b) => new Date(b.visitDate).getTime() - new Date(a.visitDate).getTime(),
  );
}

export async function getAllVisits(): Promise<Visit[]> {
  return sortByVisitDateDesc(visits);
}

export async function getVisitById(id: string): Promise<Visit | null> {
  return visits.find((visit) => visit.id === id) ?? null;
}

export async function getVisitsByPatient(patientId: string): Promise<Visit[]> {
  return sortByVisitDateDesc(visits.filter((visit) => visit.patientId === patientId));
}

export async function createVisit(input: VisitInput): Promise<Visit> {
  const now = new Date().toISOString();
  const visit: Visit = {
    id: `v-${Date.now()}`,
    ...input,
    visitDate: input.visitDate || now,
    createdAt: now,
  };

  visits.unshift(visit);
  return visit;
}
